### ISSUE TITLE
generated alt text improvement

### ISSUE THREAD

**Issue by outofambit** [shaneosullivan/gitmeme#12]
Hi, I'm enjoying using gitmeme over in https://github.com/desktop/desktop! ([example](https://github.com/desktop/desktop/pull/9873#pullrequestreview-418441629)) Thanks for making it!

I noticed today that the alt text generated by gitmeme is a bit clunky for screenreaders. For example:

<a href="https://gitme.me/image?url=https%3A%2F%2Fmedia3.giphy.com%2Fmedia%2FeEXxfHQJ0dWOrctI55%2Fgiphy.gif&token=nice" data-gitmeme-token="nice"><img src="https://media3.giphy.com/media/eEXxfHQJ0dWOrctI55/giphy.gif" title="Created by gitme.me with /nice"/></a>

is created by `/nice` and displays a "nice" gif, but the alt text says `Created by gitme.me with /nice`, which has an unnecessary preamble and an `/` right before the user search string, which means the screenreader will say "with forward slash nice" instead of "with nice".

According to [WAI](https://www.w3.org/WAI/tutorials/images/informative/#images-conveying-an-impression-or-emotion), the best text alternative is the impression the image is meant to give. **Therefore, I propose that the alt text for gitme.me content be the user supplied search string.**

(It would be nice to split the search string at `_`, since that seems to be the best way to do multi-word searches, but I think just using the search string by itself is a great improvement.)

**Comment by shaneosullivan** [comment]
Apologies for the late reply on this.  The intention with the more complex string is to let users of the repository know about Gitmem, so they can install it too.  Removing the mention of it therefore does not fulfill this requirement.

Can you think of a way to make this work with screen readers?

**Comment by outofambit** [comment]
@shaneosullivan I have two options to address that. Happy to adjust my PR to follow either of these.

## Option 1
What if we added a line of text below or next to the gif to show that info? It would get more eyes there too.

<img src="https://camo.githubusercontent.com/d42bcdf69342ec5c84978bd5292f041c0838ce8a/68747470733a2f2f6d65646961332e67697068792e636f6d2f6d656469612f654558786648514a3064574f7263744935352f67697068792e676966" alt="nice"></img>
<small><i>Created by <a href="https://gitme.me/">gitme.me</a> with /nice</i></small>


## Option 2
We could also do something much more minimal. If we add a `title` attribute to the image it will display that as the tooltip while `alt` will be used for screenreaders. This keeps the current experience the same for everyone except screenreader users, who would only hear "nice".

```html
<img src="https://camo.githubusercontent.com/d42bcdf69342ec5c84978bd5292f041c0838ce8a/68747470733a2f2f6d65646961332e67697068792e636f6d2f6d656469612f654558786648514a3064574f7263744935352f67697068792e676966"
  title="Created by gitme.me with /nice"
  alt="nice">
</img>
```

Which renders this:

<img src="https://camo.githubusercontent.com/d42bcdf69342ec5c84978bd5292f041c0838ce8a/68747470733a2f2f6d65646961332e67697068792e636f6d2f6d656469612f654558786648514a3064574f7263744935352f67697068792e676966" title="Created by gitme.me with /nice" alt="nice"></img>

**Comment by jaymzh** [comment]
Personally I'm a fan of option 2.

**Comment by shaneosullivan** [comment]
I agree, option 2 is the best of both worlds, thanks for thinking it through!  Want to send an updated PR?

**Comment by outofambit** [comment]
@shaneosullivan @jaymzh excellent, i've opened #17 with this change!
