### ISSUE TITLE
popup is nearly impossible to read

### ISSUE THREAD

**Issue by jaymzh** [shaneosullivan/gitmeme#31]
Light-gray on white is quite difficult to read:

![gitmeme-outch](https://github.com/shaneosullivan/gitmeme/assets/938467/2fc48508-596f-44f1-8f92-c72ea330c410)

**Comment by shaneosullivan** [comment]
@jaymzh Can you please test this again? It currently looks like this for me:

<img width="333" alt="Screenshot 2023-12-01 at 23 52 27" src="https://github.com/shaneosullivan/gitmeme/assets/49378/0e54a82d-9eb7-45f8-a17d-ec786b085469">
